name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
  # Also on PRs, just be careful not to publish anything
  pull_request:
  # Allow to be called from other workflows (like "release")
  workflow_call:
  # But don't trigger on tags, as they are covered by the "release.yaml" workflow

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install trunk
        run: |
          curl -sL https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz -o trunk-x86_64-unknown-linux-gnu.tar.gz
          tar xzf trunk-x86_64-unknown-linux-gnu.tar.gz
          sudo install trunk /usr/bin/trunk

      - name: Install wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            frontend/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install nodejs dependencies
        run: |
          cd frontend
          npm ci

      - name: Check formatting
        run: |
          cargo fmt --check
          cargo fmt --check --manifest-path frontend/Cargo.toml

      - name: Check frontend
        # we check the frontend before the main build, as the main build will spawn a build of the
        # frontend, embedding it into the server binary.
        run: |
          cd frontend
          cargo check --target wasm32-unknown-unknown

      - name: Check
        run: cargo check --features frontend

      - name: Generate docs
        run: |
          mkdir -p "${RUNNER_TEMP}/docs"
          cargo run --bin swio -- docs --output "${RUNNER_TEMP}/docs"

      - name: Ensure the docs are up-to-date
        run: diff -r "docs/modules/policies" "${RUNNER_TEMP}/docs"

      - name: Test
        run: cargo test -- --nocapture

      - name: Benchmark
        run: cargo bench --no-run
